spring.application.name=ApiREST-JPA-springboot-maven
spring.datasource.username=superuser
spring.datasource.url=jdbc:IRIS://192.168.100.5:1973/USER?loginTimeout=30
spring.datasource.password=fiscal2010
spring.jpa.properties.hibernate.default_schema=SQLUser
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.intersystems.jdbc.IRISDriver
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.database-platform=io.github.yurimarx.hibernateirisdialect.InterSystemsIRISDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true